/**
 * Reads the current data file (to carry over curated fields by title), and
 * serialises a new data file from synced entries.
 */
import { pathToFileURL } from "node:url";
import fs from "node:fs/promises";
import { titleKey } from "./parse.mjs";

/**
 * Dynamically import the current data file and return { exportName: array }.
 * Returns [] if the file doesn't exist yet. A cache-buster avoids stale imports.
 */
export async function loadExisting(dataFile, exportName) {
  try {
    await fs.access(dataFile);
  } catch {
    return [];
  }
  const url = pathToFileURL(dataFile).href + `?t=${Date.now()}`;
  const mod = await import(url);
  return Array.isArray(mod[exportName]) ? mod[exportName] : [];
}

/** Map existing entries by normalised title for carry-over of curated fields. */
export function indexByTitle(entries) {
  const map = new Map();
  for (const e of entries) if (e && e.title) map.set(titleKey(e.title), e);
  return map;
}

const BANNER = (exportName, folderName) =>
  `/**\n` +
  ` * AUTO-GENERATED by ops/drive-sync from Google Drive — DO NOT EDIT BY HAND.\n` +
  ` * Source: "AIS Website Content / ${folderName}". Changes here are overwritten\n` +
  ` * on the next sync. To change content, edit the files in Google Drive.\n` +
  ` */\n`;

/** Serialise entries to a data file string. Objects are emitted as pretty JSON. */
export function renderDataFile({ exportName, folderName, entries }) {
  const body = JSON.stringify(entries, null, 2);
  return `${BANNER(exportName, folderName)}export const ${exportName} = ${body};\n`;
}
